In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [4]:
def find_max(nums):
    # your code
    max = -(np.inf)

    for i in nums:
        max = i if i > max else max
    return max

print(find_max([4, 2, 9, 1, 7]))

9

In [5]:
def remove_duplicates(nums):
    # your code
    l = []
    for i in nums:
        if i not in l:
            l.append(i)
    return l


print(remove_duplicates([3, 1, 3, 2, 1, 4, 2]))
# [3, 1, 2, 4]

[3, 1, 2, 4]

In [ ]:
def flatten(nested: list) -> list:
    # [[1,2],[3,[4,5]],6] -> [1,2,3,4,5,6]
    res = []
    for i in nested:
        if i.dtype() == list:
            

print(flatten([[1,2],[3,[4,5]],6]))

In [10]:
def flatten(nested: list) -> list:
    res = []
    for i in nested:
        # 1. Correct way to check if the item is a list
        if isinstance(i, list):
            # 2. Recursively flatten and combine the sublist
            res.extend(flatten(i))
        else:
            # 3. Add individual elements directly
            res.append(i)
    return res

print(flatten([[1, 2], [3, [4, 5]], 6]))
# Output: [1, 2, 3, 4, 5, 6]

print(flatten([1, [2, 3], [[4, 5], 6], [7]]))

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]

In [13]:
def word_freq(s: str) -> dict:
    words = list(s.split(' '))
    count_dict = {}
    for i in words:
        if i in count_dict:
            count_dict[i] += 1
        else:
            count_dict[i] = 1
    return count_dict

print(word_freq("jeans jeans shirts jeans shirts pants"))

{'jeans': 3, 'shirts': 2, 'pants': 1}

In [ ]:
prices = [499, 999, 1499, 1999, 2499, 2999]

# use lambda + filter/map: return prices > 1000, each reduced by 10%
def discounted_high_prices(prices: list) -> list:
    pass

print(discounted_high_prices(prices))

In [19]:
def first_non_repeating(s):
    # your code
    seen = set()
    res = []
    for i in s:
        if i not in seen:
            res.append(i)
            seen.add(i)
        else:
            res.remove(i)
    print(res)
    return res[0]

print(first_non_repeating("aabbcddeekmsl"))
# c

['c', 'k', 'm', 's', 'l']
c

In [21]:
products = [
    {"product": "Jeans", "sales": 500},
    {"product": "Shirt", "sales": 300},
    {"product": "Shoes", "sales": 700},
    {"product": "Jacket", "sales": 450},
]

# Sort by sales descending using lambda.

prod_sorted = sorted(products, key = lambda x:x['sales'], reverse=True)
prod_sorted

[{'product': 'Shoes', 'sales': 700},
 {'product': 'Jeans', 'sales': 500},
 {'product': 'Jacket', 'sales': 450},
 {'product': 'Shirt', 'sales': 300}]

In [25]:
# Return products with price > 500.
result = list(filter(lambda x: x["sales"] > 500, products))

print(result)

[{'product': 'Shoes', 'sales': 700}]

In [27]:
prices = [1000, 1500, 2000, 2500]

# Apply a 10% discount.

res = list(map(lambda x: x*0.9, prices))
res

[900.0, 1350.0, 1800.0, 2250.0]

In [29]:
# {
#     "jeans": 5,
#     "shirt": 5,
#     "shoes": 5,
#     "jacket": 6
# }
# where the value is the length.

products = ["jeans", "shirt", "shoes", "jacket"]
res = {}
for i in products:
    if i not in res:
        res[i] = len(i)
res

{'jeans': 5, 'shirt': 5, 'shoes': 5, 'jacket': 6}

In [30]:
# merge 2 dictionoaries

sales = {
    "jeans": 1000,
    "shirt": 500
}

units = {
    "jeans": 10,
    "shirt": 5
}

# {
#     "jeans": {"sales": 1000, "units": 10},
#     "shirt": {"sales": 500, "units": 5}
# }

res = {}
for i in sales:
    res[i] = {
        "sales": sales[i],
        "units": units[i]
    }
res

{'jeans': {'sales': 1000, 'units': 10}, 'shirt': {'sales': 500, 'units': 5}}

In [36]:
transactions = [
    {"product": "501", "price": 100, "units": 2},
    {"product": "502", "price": 200, "units": 1},
    {"product": "501", "price": 120, "units": 3},
    {"product": "502", "price": 150, "units": 2},
]

# Calculate total revenue by product.
# {
#     "501": 560,
#     "502": 500
# }

res = {}
for dic in transactions:
    for key, value in dic.items():
        if key == 'product':
            if dic[key] in res:
                res[dic[key]] += dic['price']
            else:
                res[dic[key]] = dic['price']

res

{'501': 220, '502': 350}

In [37]:
560/5

112.0

In [38]:
500/3

166.66666666666666

In [39]:
# {
#     "501": {
#         "revenue": 560,
#         "units": 5,
#         "asp": 112
#     },
#     "502": {
#         "revenue": 500,
#         "units": 3,
#         "asp": 166.66
#     }
# }


transactions = [
    {"product": "501", "price": 100, "units": 2},
    {"product": "502", "price": 200, "units": 1},
    {"product": "501", "price": 120, "units": 3},
    {"product": "502", "price": 150, "units": 2},
]

res = {}

for dic in transactions:
    product = dic["product"]
    revenue = dic["price"] * dic["units"]
    units = dic["units"]

    if product not in res:
        res[product] = {
            "revenue": 0,
            "units": 0
        }

    res[product]["revenue"] += revenue
    res[product]["units"] += units

for product in res:
    res[product]["asp"] = res[product]["revenue"] / res[product]["units"]

res

{'501': {'revenue': 560, 'units': 5, 'asp': 112.0},
 '502': {'revenue': 500, 'units': 3, 'asp': 166.66666666666666}}

In [76]:
import pandas as pd
import numpy as np

data = {
    "customer_id": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20
    ],

    "product": [
        "Jeans", "Shirt", "Jeans", "Shoes", "Shirt",
        "Jeans", "Shoes", "T-Shirt", "Jeans", "Jacket",
        "Shirt", "Shoes", "T-Shirt", "Jeans", "Jacket",
        "Shirt", "Shoes", "Jeans", "T-Shirt", "Jacket"
    ],

    "category": [
        "Bottomwear", "Topwear", "Bottomwear", "Footwear", "Topwear",
        "Bottomwear", "Footwear", "Topwear", "Bottomwear", "Outerwear",
        "Topwear", "Footwear", "Topwear", "Bottomwear", "Outerwear",
        "Topwear", "Footwear", "Bottomwear", "Topwear", "Outerwear"
    ],

    "price": [
        2000, 1000, 2200, 3000, np.nan,
        1800, 3200, 800, 2100, 4000,
        1200, 2800, 900, 1900, 4500,
        1100, 3500, 2300, 850, np.nan
    ],

    "units": [
        2, 1, 3, 1, 2,
        4, 2, 5, 1, 2,
        3, 2, 4, 3, 1,
        2, 3, 5, 2, 2
    ],

    "discount": [
        0, 10, 20, 0, 15,
        np.nan, 25, 5, 10, 30,
        20, 0, 8, 12, np.nan,
        18, 22, 0, 5, 35
    ],

    "region": [
        "South", "North", "South", "West", "North",
        "South", "West", "North", "East", "South",
        "North", "West", "East", "South", "East",
        "North", "West", "South", "East", "South"
    ]
}

df = pd.DataFrame(data)

df

    customer_id  product    category   price  units  discount region
0             1    Jeans  Bottomwear  2000.0      2       0.0  South
1             2    Shirt     Topwear  1000.0      1      10.0  North
2             3    Jeans  Bottomwear  2200.0      3      20.0  South
3             4    Shoes    Footwear  3000.0      1       0.0   West
4             5    Shirt     Topwear     NaN      2      15.0  North
5             6    Jeans  Bottomwear  1800.0      4       NaN  South
6             7    Shoes    Footwear  3200.0      2      25.0   West
7             8  T-Shirt     Topwear   800.0      5       5.0  North
8             9    Jeans  Bottomwear  2100.0      1      10.0   East
9            10   Jacket   Outerwear  4000.0      2      30.0  South
10           11    Shirt     Topwear  1200.0      3      20.0  North
11           12    Shoes    Footwear  2800.0      2       0.0   West
12           13  T-Shirt     Topwear   900.0      4       8.0   East
13           14    Jeans  Bottomwear  1900.0      3      12.0  South
14           15   Jacket   Outerwear  4500.0      1       NaN   East
15           16    Shirt     Topwear  1100.0      2      18.0  North
16           17    Shoes    Footwear  3500.0      3      22.0   West
17           18    Jeans  Bottomwear  2300.0      5       0.0  South
18           19  T-Shirt     Topwear   850.0      2       5.0   East
19           20   Jacket   Outerwear     NaN      2      35.0  South

In [78]:
print(df.head(3))
print(df.shape)
print(df.columns)
df.info()
df.describe()

   customer_id product    category   price  units  discount region
0            1   Jeans  Bottomwear  2000.0      2       0.0  South
1            2   Shirt     Topwear  1000.0      1      10.0  North
2            3   Jeans  Bottomwear  2200.0      3      20.0  South
(20, 7)
Index(['customer_id', 'product', 'category', 'price', 'units', 'discount',
       'region'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  20 non-null     int64
 1   product      20 non-null     object
 2   category     20 non-null     object
 3   price        18 non-null     float64
 4   units        20 non-null     int64
 5   discount     18 non-null     float64
 6   region       20 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.2+ KB

       customer_id        price      units   discount
count     20.00000    18.000000  20.000000  18.000000
mean      10.50000  2175.000000   2.500000  13.055556
std        5.91608  1128.279534   1.235442  10.772908
min        1.00000   800.000000   1.000000   0.000000
25%        5.75000  1125.000000   2.000000   5.000000
50%       10.50000  2050.000000   2.000000  11.000000
75%       15.25000  2950.000000   3.000000  20.000000
max       20.00000  4500.000000   5.000000  35.000000

In [79]:
df.isna().sum()

customer_id    0
product        0
category       0
price          2
units          0
discount       2
region         0
dtype: int64

In [80]:
df['discount'].fillna(0, inplace=True)
df

C:\Users\tsais\AppData\Local\Temp\ipykernel_25040\3341028509.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['discount'].fillna(0, inplace=True)

    customer_id  product    category   price  units  discount region
0             1    Jeans  Bottomwear  2000.0      2       0.0  South
1             2    Shirt     Topwear  1000.0      1      10.0  North
2             3    Jeans  Bottomwear  2200.0      3      20.0  South
3             4    Shoes    Footwear  3000.0      1       0.0   West
4             5    Shirt     Topwear     NaN      2      15.0  North
5             6    Jeans  Bottomwear  1800.0      4       0.0  South
6             7    Shoes    Footwear  3200.0      2      25.0   West
7             8  T-Shirt     Topwear   800.0      5       5.0  North
8             9    Jeans  Bottomwear  2100.0      1      10.0   East
9            10   Jacket   Outerwear  4000.0      2      30.0  South
10           11    Shirt     Topwear  1200.0      3      20.0  North
11           12    Shoes    Footwear  2800.0      2       0.0   West
12           13  T-Shirt     Topwear   900.0      4       8.0   East
13           14    Jeans  Bottomwear  1900.0      3      12.0  South
14           15   Jacket   Outerwear  4500.0      1       0.0   East
15           16    Shirt     Topwear  1100.0      2      18.0  North
16           17    Shoes    Footwear  3500.0      3      22.0   West
17           18    Jeans  Bottomwear  2300.0      5       0.0  South
18           19  T-Shirt     Topwear   850.0      2       5.0   East
19           20   Jacket   Outerwear     NaN      2      35.0  South

In [81]:
df['price'] = df['price'].fillna(df['price'].median())
df

    customer_id  product    category   price  units  discount region
0             1    Jeans  Bottomwear  2000.0      2       0.0  South
1             2    Shirt     Topwear  1000.0      1      10.0  North
2             3    Jeans  Bottomwear  2200.0      3      20.0  South
3             4    Shoes    Footwear  3000.0      1       0.0   West
4             5    Shirt     Topwear  2050.0      2      15.0  North
5             6    Jeans  Bottomwear  1800.0      4       0.0  South
6             7    Shoes    Footwear  3200.0      2      25.0   West
7             8  T-Shirt     Topwear   800.0      5       5.0  North
8             9    Jeans  Bottomwear  2100.0      1      10.0   East
9            10   Jacket   Outerwear  4000.0      2      30.0  South
10           11    Shirt     Topwear  1200.0      3      20.0  North
11           12    Shoes    Footwear  2800.0      2       0.0   West
12           13  T-Shirt     Topwear   900.0      4       8.0   East
13           14    Jeans  Bottomwear  1900.0      3      12.0  South
14           15   Jacket   Outerwear  4500.0      1       0.0   East
15           16    Shirt     Topwear  1100.0      2      18.0  North
16           17    Shoes    Footwear  3500.0      3      22.0   West
17           18    Jeans  Bottomwear  2300.0      5       0.0  South
18           19  T-Shirt     Topwear   850.0      2       5.0   East
19           20   Jacket   Outerwear  2050.0      2      35.0  South

In [82]:
df['revenue'] = df['price'] * df['units']
df

    customer_id  product    category   price  units  discount region  revenue
0             1    Jeans  Bottomwear  2000.0      2       0.0  South   4000.0
1             2    Shirt     Topwear  1000.0      1      10.0  North   1000.0
2             3    Jeans  Bottomwear  2200.0      3      20.0  South   6600.0
3             4    Shoes    Footwear  3000.0      1       0.0   West   3000.0
4             5    Shirt     Topwear  2050.0      2      15.0  North   4100.0
5             6    Jeans  Bottomwear  1800.0      4       0.0  South   7200.0
6             7    Shoes    Footwear  3200.0      2      25.0   West   6400.0
7             8  T-Shirt     Topwear   800.0      5       5.0  North   4000.0
8             9    Jeans  Bottomwear  2100.0      1      10.0   East   2100.0
9            10   Jacket   Outerwear  4000.0      2      30.0  South   8000.0
10           11    Shirt     Topwear  1200.0      3      20.0  North   3600.0
11           12    Shoes    Footwear  2800.0      2       0.0   West   5600.0
12           13  T-Shirt     Topwear   900.0      4       8.0   East   3600.0
13           14    Jeans  Bottomwear  1900.0      3      12.0  South   5700.0
14           15   Jacket   Outerwear  4500.0      1       0.0   East   4500.0
15           16    Shirt     Topwear  1100.0      2      18.0  North   2200.0
16           17    Shoes    Footwear  3500.0      3      22.0   West  10500.0
17           18    Jeans  Bottomwear  2300.0      5       0.0  South  11500.0
18           19  T-Shirt     Topwear   850.0      2       5.0   East   1700.0
19           20   Jacket   Outerwear  2050.0      2      35.0  South   4100.0

In [83]:
df["final_price"] = df.apply(lambda row: row["price"] * (1 - row["discount"] / 100), axis=1)
df

,customer_id,product,category,price,units,discount,region,revenue,final_price
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5

In [84]:
df['promo_flag'] = np.where(df['discount'] > 0, 1, 0)
df

,customer_id,product,category,price,units,discount,region,revenue,final_price,promo_flag
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0,0
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0,1
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0,1
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0,0
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5,1
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0,0
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0,1
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0,1
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0,1
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0,1
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0,1
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0,0
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0,1
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0,1
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0,0
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0,1
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0,1
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0,0
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5,1
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5,1

In [85]:
conditions = [
    df['discount'] == 0,
    df['discount'].between(1, 10),
    df['discount'].between(11, 20),
    df['discount'] > 20
]

choices = [
    "No discount",
    "Low",
    "Medium",
    "High"
]

df['discount_category'] = np.select(conditions, choices, default="Unknowm")
df

,customer_id,product,category,price,units,discount,region,revenue,final_price,promo_flag,discount_category
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0,0,No discount
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0,1,Low
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0,1,Medium
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0,0,No discount
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5,1,Medium
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0,0,No discount
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0,1,High
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0,1,Low
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0,1,Low
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0,1,High
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0,1,Medium
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0,0,No discount
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0,1,Low
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0,1,Medium
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0,0,No discount
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0,1,Medium
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0,1,High
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0,0,No discount
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5,1,Low
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5,1,High

In [86]:
df = df.sort_values(by = ['category', 'revenue'], ascending=[True, False])
df

,customer_id,product,category,price,units,discount,region,revenue,final_price,promo_flag,discount_category
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0,0,No discount
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0,0,No discount
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0,1,Medium
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0,1,Medium
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0,0,No discount
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0,1,Low
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0,1,High
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0,1,High
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0,0,No discount
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0,0,No discount
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0,1,High
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0,0,No discount
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5,1,High
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5,1,Medium
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0,1,Low
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0,1,Medium
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0,1,Low
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0,1,Medium
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5,1,Low
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0,1,Low

In [87]:
df.groupby('product')[['revenue','units']].sum()

         revenue  units
product
Jacket   16600.0      5
Jeans    37100.0     18
Shirt    10900.0      8
Shoes    25500.0      8
T-Shirt   9300.0     11

In [89]:
res = df.groupby('product').agg({'revenue': 'sum',
                           'units': 'sum',
                           })
res['asp'] = res['revenue'] / res['units']
res

         revenue  units          asp
product
Jacket   16600.0      5  3320.000000
Jeans    37100.0     18  2061.111111
Shirt    10900.0      8  1362.500000
Shoes    25500.0      8  3187.500000
T-Shirt   9300.0     11   845.454545

In [90]:
df.groupby(by=['region', 'product'])[['revenue', 'units']].sum()

                revenue  units
region product
East   Jacket    4500.0      1
       Jeans     2100.0      1
       T-Shirt   5300.0      6
North  Shirt    10900.0      8
       T-Shirt   4000.0      5
South  Jacket   12100.0      4
       Jeans    35000.0     17
West   Shoes    25500.0      8

In [91]:
df.groupby('product')['revenue'].sum().sort_values(ascending=False).head(1)

product
Jeans    37100.0
Name: revenue, dtype: float64

In [92]:
df.groupby('product')['revenue'].sum().idxmax()

'Jeans'

In [93]:
df.groupby(["region", "product"])["revenue"].sum()

region  product
East    Jacket      4500.0
        Jeans       2100.0
        T-Shirt     5300.0
North   Shirt      10900.0
        T-Shirt     4000.0
South   Jacket     12100.0
        Jeans      35000.0
West    Shoes      25500.0
Name: revenue, dtype: float64

In [96]:
revenue = (
    df.groupby(["region", "product"])["revenue"]
      .sum()
      .reset_index()
)

result = (
    revenue.loc[
        revenue.groupby("region")["revenue"].idxmax()
    ]
)

result

  region  product  revenue
2   East  T-Shirt   5300.0
3  North    Shirt  10900.0
6  South    Jeans  35000.0
7   West    Shoes  25500.0