In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [4]:
def find_max(nums):
    # your code
    max = -(np.inf)

    for i in nums:
        max = i if i > max else max
    return max

print(find_max([4, 2, 9, 1, 7]))

9

In [5]:
def remove_duplicates(nums):
    # your code
    l = []
    for i in nums:
        if i not in l:
            l.append(i)
    return l


print(remove_duplicates([3, 1, 3, 2, 1, 4, 2]))
# [3, 1, 2, 4]

[3, 1, 2, 4]

In [ ]:
def flatten(nested: list) -> list:
    # [[1,2],[3,[4,5]],6] -> [1,2,3,4,5,6]
    res = []
    for i in nested:
        if i.dtype() == list:
            

print(flatten([[1,2],[3,[4,5]],6]))

In [10]:
def flatten(nested: list) -> list:
    res = []
    for i in nested:
        # 1. Correct way to check if the item is a list
        if isinstance(i, list):
            # 2. Recursively flatten and combine the sublist
            res.extend(flatten(i))
        else:
            # 3. Add individual elements directly
            res.append(i)
    return res

print(flatten([[1, 2], [3, [4, 5]], 6]))
# Output: [1, 2, 3, 4, 5, 6]

print(flatten([1, [2, 3], [[4, 5], 6], [7]]))

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]

In [13]:
def word_freq(s: str) -> dict:
    words = list(s.split(' '))
    count_dict = {}
    for i in words:
        if i in count_dict:
            count_dict[i] += 1
        else:
            count_dict[i] = 1
    return count_dict

print(word_freq("jeans jeans shirts jeans shirts pants"))

{'jeans': 3, 'shirts': 2, 'pants': 1}

In [ ]:
prices = [499, 999, 1499, 1999, 2499, 2999]

# use lambda + filter/map: return prices > 1000, each reduced by 10%
def discounted_high_prices(prices: list) -> list:
    pass

print(discounted_high_prices(prices))

In [19]:
def first_non_repeating(s):
    # your code
    seen = set()
    res = []
    for i in s:
        if i not in seen:
            res.append(i)
            seen.add(i)
        else:
            res.remove(i)
    print(res)
    return res[0]

print(first_non_repeating("aabbcddeekmsl"))
# c

['c', 'k', 'm', 's', 'l']
c

In [21]:
products = [
    {"product": "Jeans", "sales": 500},
    {"product": "Shirt", "sales": 300},
    {"product": "Shoes", "sales": 700},
    {"product": "Jacket", "sales": 450},
]

# Sort by sales descending using lambda.

prod_sorted = sorted(products, key = lambda x:x['sales'], reverse=True)
prod_sorted

[{'product': 'Shoes', 'sales': 700},
 {'product': 'Jeans', 'sales': 500},
 {'product': 'Jacket', 'sales': 450},
 {'product': 'Shirt', 'sales': 300}]

In [25]:
# Return products with price > 500.
result = list(filter(lambda x: x["sales"] > 500, products))

print(result)

[{'product': 'Shoes', 'sales': 700}]

In [27]:
prices = [1000, 1500, 2000, 2500]

# Apply a 10% discount.

res = list(map(lambda x: x*0.9, prices))
res

[900.0, 1350.0, 1800.0, 2250.0]

In [29]:
# {
#     "jeans": 5,
#     "shirt": 5,
#     "shoes": 5,
#     "jacket": 6
# }
# where the value is the length.

products = ["jeans", "shirt", "shoes", "jacket"]
res = {}
for i in products:
    if i not in res:
        res[i] = len(i)
res

{'jeans': 5, 'shirt': 5, 'shoes': 5, 'jacket': 6}

In [30]:
# merge 2 dictionoaries

sales = {
    "jeans": 1000,
    "shirt": 500
}

units = {
    "jeans": 10,
    "shirt": 5
}

# {
#     "jeans": {"sales": 1000, "units": 10},
#     "shirt": {"sales": 500, "units": 5}
# }

res = {}
for i in sales:
    res[i] = {
        "sales": sales[i],
        "units": units[i]
    }
res

{'jeans': {'sales': 1000, 'units': 10}, 'shirt': {'sales': 500, 'units': 5}}

In [36]:
transactions = [
    {"product": "501", "price": 100, "units": 2},
    {"product": "502", "price": 200, "units": 1},
    {"product": "501", "price": 120, "units": 3},
    {"product": "502", "price": 150, "units": 2},
]

# Calculate total revenue by product.
# {
#     "501": 560,
#     "502": 500
# }

res = {}
for dic in transactions:
    for key, value in dic.items():
        if key == 'product':
            if dic[key] in res:
                res[dic[key]] += dic['price']
            else:
                res[dic[key]] = dic['price']

res

{'501': 220, '502': 350}

In [37]:
560/5

112.0

In [38]:
500/3

166.66666666666666

In [39]:
# {
#     "501": {
#         "revenue": 560,
#         "units": 5,
#         "asp": 112
#     },
#     "502": {
#         "revenue": 500,
#         "units": 3,
#         "asp": 166.66
#     }
# }


transactions = [
    {"product": "501", "price": 100, "units": 2},
    {"product": "502", "price": 200, "units": 1},
    {"product": "501", "price": 120, "units": 3},
    {"product": "502", "price": 150, "units": 2},
]

res = {}

for dic in transactions:
    product = dic["product"]
    revenue = dic["price"] * dic["units"]
    units = dic["units"]

    if product not in res:
        res[product] = {
            "revenue": 0,
            "units": 0
        }

    res[product]["revenue"] += revenue
    res[product]["units"] += units

for product in res:
    res[product]["asp"] = res[product]["revenue"] / res[product]["units"]

res

{'501': {'revenue': 560, 'units': 5, 'asp': 112.0},
 '502': {'revenue': 500, 'units': 3, 'asp': 166.66666666666666}}

In [76]:
import pandas as pd
import numpy as np

data = {
    "customer_id": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20
    ],

    "product": [
        "Jeans", "Shirt", "Jeans", "Shoes", "Shirt",
        "Jeans", "Shoes", "T-Shirt", "Jeans", "Jacket",
        "Shirt", "Shoes", "T-Shirt", "Jeans", "Jacket",
        "Shirt", "Shoes", "Jeans", "T-Shirt", "Jacket"
    ],

    "category": [
        "Bottomwear", "Topwear", "Bottomwear", "Footwear", "Topwear",
        "Bottomwear", "Footwear", "Topwear", "Bottomwear", "Outerwear",
        "Topwear", "Footwear", "Topwear", "Bottomwear", "Outerwear",
        "Topwear", "Footwear", "Bottomwear", "Topwear", "Outerwear"
    ],

    "price": [
        2000, 1000, 2200, 3000, np.nan,
        1800, 3200, 800, 2100, 4000,
        1200, 2800, 900, 1900, 4500,
        1100, 3500, 2300, 850, np.nan
    ],

    "units": [
        2, 1, 3, 1, 2,
        4, 2, 5, 1, 2,
        3, 2, 4, 3, 1,
        2, 3, 5, 2, 2
    ],

    "discount": [
        0, 10, 20, 0, 15,
        np.nan, 25, 5, 10, 30,
        20, 0, 8, 12, np.nan,
        18, 22, 0, 5, 35
    ],

    "region": [
        "South", "North", "South", "West", "North",
        "South", "West", "North", "East", "South",
        "North", "West", "East", "South", "East",
        "North", "West", "South", "East", "South"
    ]
}

df = pd.DataFrame(data)

df

    customer_id  product    category   price  units  discount region
0             1    Jeans  Bottomwear  2000.0      2       0.0  South
1             2    Shirt     Topwear  1000.0      1      10.0  North
2             3    Jeans  Bottomwear  2200.0      3      20.0  South
3             4    Shoes    Footwear  3000.0      1       0.0   West
4             5    Shirt     Topwear     NaN      2      15.0  North
5             6    Jeans  Bottomwear  1800.0      4       NaN  South
6             7    Shoes    Footwear  3200.0      2      25.0   West
7             8  T-Shirt     Topwear   800.0      5       5.0  North
8             9    Jeans  Bottomwear  2100.0      1      10.0   East
9            10   Jacket   Outerwear  4000.0      2      30.0  South
10           11    Shirt     Topwear  1200.0      3      20.0  North
11           12    Shoes    Footwear  2800.0      2       0.0   West
12           13  T-Shirt     Topwear   900.0      4       8.0   East
13           14    Jeans  Bottomwear  1900.0      3      12.0  South
14           15   Jacket   Outerwear  4500.0      1       NaN   East
15           16    Shirt     Topwear  1100.0      2      18.0  North
16           17    Shoes    Footwear  3500.0      3      22.0   West
17           18    Jeans  Bottomwear  2300.0      5       0.0  South
18           19  T-Shirt     Topwear   850.0      2       5.0   East
19           20   Jacket   Outerwear     NaN      2      35.0  South

In [78]:
print(df.head(3))
print(df.shape)
print(df.columns)
df.info()
df.describe()

   customer_id product    category   price  units  discount region
0            1   Jeans  Bottomwear  2000.0      2       0.0  South
1            2   Shirt     Topwear  1000.0      1      10.0  North
2            3   Jeans  Bottomwear  2200.0      3      20.0  South
(20, 7)
Index(['customer_id', 'product', 'category', 'price', 'units', 'discount',
       'region'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  20 non-null     int64
 1   product      20 non-null     object
 2   category     20 non-null     object
 3   price        18 non-null     float64
 4   units        20 non-null     int64
 5   discount     18 non-null     float64
 6   region       20 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.2+ KB

       customer_id        price      units   discount
count     20.00000    18.000000  20.000000  18.000000
mean      10.50000  2175.000000   2.500000  13.055556
std        5.91608  1128.279534   1.235442  10.772908
min        1.00000   800.000000   1.000000   0.000000
25%        5.75000  1125.000000   2.000000   5.000000
50%       10.50000  2050.000000   2.000000  11.000000
75%       15.25000  2950.000000   3.000000  20.000000
max       20.00000  4500.000000   5.000000  35.000000

In [79]:
df.isna().sum()

customer_id    0
product        0
category       0
price          2
units          0
discount       2
region         0
dtype: int64

In [80]:
df['discount'].fillna(0, inplace=True)
df

C:\Users\tsais\AppData\Local\Temp\ipykernel_25040\3341028509.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['discount'].fillna(0, inplace=True)

    customer_id  product    category   price  units  discount region
0             1    Jeans  Bottomwear  2000.0      2       0.0  South
1             2    Shirt     Topwear  1000.0      1      10.0  North
2             3    Jeans  Bottomwear  2200.0      3      20.0  South
3             4    Shoes    Footwear  3000.0      1       0.0   West
4             5    Shirt     Topwear     NaN      2      15.0  North
5             6    Jeans  Bottomwear  1800.0      4       0.0  South
6             7    Shoes    Footwear  3200.0      2      25.0   West
7             8  T-Shirt     Topwear   800.0      5       5.0  North
8             9    Jeans  Bottomwear  2100.0      1      10.0   East
9            10   Jacket   Outerwear  4000.0      2      30.0  South
10           11    Shirt     Topwear  1200.0      3      20.0  North
11           12    Shoes    Footwear  2800.0      2       0.0   West
12           13  T-Shirt     Topwear   900.0      4       8.0   East
13           14    Jeans  Bottomwear  1900.0      3      12.0  South
14           15   Jacket   Outerwear  4500.0      1       0.0   East
15           16    Shirt     Topwear  1100.0      2      18.0  North
16           17    Shoes    Footwear  3500.0      3      22.0   West
17           18    Jeans  Bottomwear  2300.0      5       0.0  South
18           19  T-Shirt     Topwear   850.0      2       5.0   East
19           20   Jacket   Outerwear     NaN      2      35.0  South

In [81]:
df['price'] = df['price'].fillna(df['price'].median())
df

    customer_id  product    category   price  units  discount region
0             1    Jeans  Bottomwear  2000.0      2       0.0  South
1             2    Shirt     Topwear  1000.0      1      10.0  North
2             3    Jeans  Bottomwear  2200.0      3      20.0  South
3             4    Shoes    Footwear  3000.0      1       0.0   West
4             5    Shirt     Topwear  2050.0      2      15.0  North
5             6    Jeans  Bottomwear  1800.0      4       0.0  South
6             7    Shoes    Footwear  3200.0      2      25.0   West
7             8  T-Shirt     Topwear   800.0      5       5.0  North
8             9    Jeans  Bottomwear  2100.0      1      10.0   East
9            10   Jacket   Outerwear  4000.0      2      30.0  South
10           11    Shirt     Topwear  1200.0      3      20.0  North
11           12    Shoes    Footwear  2800.0      2       0.0   West
12           13  T-Shirt     Topwear   900.0      4       8.0   East
13           14    Jeans  Bottomwear  1900.0      3      12.0  South
14           15   Jacket   Outerwear  4500.0      1       0.0   East
15           16    Shirt     Topwear  1100.0      2      18.0  North
16           17    Shoes    Footwear  3500.0      3      22.0   West
17           18    Jeans  Bottomwear  2300.0      5       0.0  South
18           19  T-Shirt     Topwear   850.0      2       5.0   East
19           20   Jacket   Outerwear  2050.0      2      35.0  South

In [82]:
df['revenue'] = df['price'] * df['units']
df

    customer_id  product    category   price  units  discount region  revenue
0             1    Jeans  Bottomwear  2000.0      2       0.0  South   4000.0
1             2    Shirt     Topwear  1000.0      1      10.0  North   1000.0
2             3    Jeans  Bottomwear  2200.0      3      20.0  South   6600.0
3             4    Shoes    Footwear  3000.0      1       0.0   West   3000.0
4             5    Shirt     Topwear  2050.0      2      15.0  North   4100.0
5             6    Jeans  Bottomwear  1800.0      4       0.0  South   7200.0
6             7    Shoes    Footwear  3200.0      2      25.0   West   6400.0
7             8  T-Shirt     Topwear   800.0      5       5.0  North   4000.0
8             9    Jeans  Bottomwear  2100.0      1      10.0   East   2100.0
9            10   Jacket   Outerwear  4000.0      2      30.0  South   8000.0
10           11    Shirt     Topwear  1200.0      3      20.0  North   3600.0
11           12    Shoes    Footwear  2800.0      2       0.0   West   5600.0
12           13  T-Shirt     Topwear   900.0      4       8.0   East   3600.0
13           14    Jeans  Bottomwear  1900.0      3      12.0  South   5700.0
14           15   Jacket   Outerwear  4500.0      1       0.0   East   4500.0
15           16    Shirt     Topwear  1100.0      2      18.0  North   2200.0
16           17    Shoes    Footwear  3500.0      3      22.0   West  10500.0
17           18    Jeans  Bottomwear  2300.0      5       0.0  South  11500.0
18           19  T-Shirt     Topwear   850.0      2       5.0   East   1700.0
19           20   Jacket   Outerwear  2050.0      2      35.0  South   4100.0

In [83]:
df["final_price"] = df.apply(lambda row: row["price"] * (1 - row["discount"] / 100), axis=1)
df

,customer_id,product,category,price,units,discount,region,revenue,final_price
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5

In [84]:
df['promo_flag'] = np.where(df['discount'] > 0, 1, 0)
df

,customer_id,product,category,price,units,discount,region,revenue,final_price,promo_flag
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0,0
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0,1
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0,1
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0,0
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5,1
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0,0
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0,1
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0,1
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0,1
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0,1
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0,1
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0,0
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0,1
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0,1
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0,0
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0,1
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0,1
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0,0
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5,1
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5,1

In [85]:
conditions = [
    df['discount'] == 0,
    df['discount'].between(1, 10),
    df['discount'].between(11, 20),
    df['discount'] > 20
]

choices = [
    "No discount",
    "Low",
    "Medium",
    "High"
]

df['discount_category'] = np.select(conditions, choices, default="Unknowm")
df

,customer_id,product,category,price,units,discount,region,revenue,final_price,promo_flag,discount_category
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0,0,No discount
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0,1,Low
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0,1,Medium
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0,0,No discount
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5,1,Medium
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0,0,No discount
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0,1,High
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0,1,Low
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0,1,Low
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0,1,High
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0,1,Medium
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0,0,No discount
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0,1,Low
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0,1,Medium
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0,0,No discount
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0,1,Medium
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0,1,High
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0,0,No discount
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5,1,Low
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5,1,High

In [86]:
df = df.sort_values(by = ['category', 'revenue'], ascending=[True, False])
df

,customer_id,product,category,price,units,discount,region,revenue,final_price,promo_flag,discount_category
17,18,Jeans,Bottomwear,2300.0,5,0.0,South,11500.0,2300.0,0,No discount
5,6,Jeans,Bottomwear,1800.0,4,0.0,South,7200.0,1800.0,0,No discount
2,3,Jeans,Bottomwear,2200.0,3,20.0,South,6600.0,1760.0,1,Medium
13,14,Jeans,Bottomwear,1900.0,3,12.0,South,5700.0,1672.0,1,Medium
0,1,Jeans,Bottomwear,2000.0,2,0.0,South,4000.0,2000.0,0,No discount
8,9,Jeans,Bottomwear,2100.0,1,10.0,East,2100.0,1890.0,1,Low
16,17,Shoes,Footwear,3500.0,3,22.0,West,10500.0,2730.0,1,High
6,7,Shoes,Footwear,3200.0,2,25.0,West,6400.0,2400.0,1,High
11,12,Shoes,Footwear,2800.0,2,0.0,West,5600.0,2800.0,0,No discount
3,4,Shoes,Footwear,3000.0,1,0.0,West,3000.0,3000.0,0,No discount
9,10,Jacket,Outerwear,4000.0,2,30.0,South,8000.0,2800.0,1,High
14,15,Jacket,Outerwear,4500.0,1,0.0,East,4500.0,4500.0,0,No discount
19,20,Jacket,Outerwear,2050.0,2,35.0,South,4100.0,1332.5,1,High
4,5,Shirt,Topwear,2050.0,2,15.0,North,4100.0,1742.5,1,Medium
7,8,T-Shirt,Topwear,800.0,5,5.0,North,4000.0,760.0,1,Low
10,11,Shirt,Topwear,1200.0,3,20.0,North,3600.0,960.0,1,Medium
12,13,T-Shirt,Topwear,900.0,4,8.0,East,3600.0,828.0,1,Low
15,16,Shirt,Topwear,1100.0,2,18.0,North,2200.0,902.0,1,Medium
18,19,T-Shirt,Topwear,850.0,2,5.0,East,1700.0,807.5,1,Low
1,2,Shirt,Topwear,1000.0,1,10.0,North,1000.0,900.0,1,Low

In [87]:
df.groupby('product')[['revenue','units']].sum()

         revenue  units
product
Jacket   16600.0      5
Jeans    37100.0     18
Shirt    10900.0      8
Shoes    25500.0      8
T-Shirt   9300.0     11

In [89]:
res = df.groupby('product').agg({'revenue': 'sum',
                           'units': 'sum',
                           })
res['asp'] = res['revenue'] / res['units']
res

         revenue  units          asp
product
Jacket   16600.0      5  3320.000000
Jeans    37100.0     18  2061.111111
Shirt    10900.0      8  1362.500000
Shoes    25500.0      8  3187.500000
T-Shirt   9300.0     11   845.454545

In [90]:
df.groupby(by=['region', 'product'])[['revenue', 'units']].sum()

                revenue  units
region product
East   Jacket    4500.0      1
       Jeans     2100.0      1
       T-Shirt   5300.0      6
North  Shirt    10900.0      8
       T-Shirt   4000.0      5
South  Jacket   12100.0      4
       Jeans    35000.0     17
West   Shoes    25500.0      8

In [91]:
df.groupby('product')['revenue'].sum().sort_values(ascending=False).head(1)

product
Jeans    37100.0
Name: revenue, dtype: float64

In [92]:
df.groupby('product')['revenue'].sum().idxmax()

'Jeans'

In [93]:
df.groupby(["region", "product"])["revenue"].sum()

region  product
East    Jacket      4500.0
        Jeans       2100.0
        T-Shirt     5300.0
North   Shirt      10900.0
        T-Shirt     4000.0
South   Jacket     12100.0
        Jeans      35000.0
West    Shoes      25500.0
Name: revenue, dtype: float64

In [96]:
revenue = (
    df.groupby(["region", "product"])["revenue"]
      .sum()
      .reset_index()
)

result = (
    revenue.loc[
        revenue.groupby("region")["revenue"].idxmax()
    ]
)

result

  region  product  revenue
2   East  T-Shirt   5300.0
3  North    Shirt  10900.0
6  South    Jeans  35000.0
7   West    Shoes  25500.0

## Postgres Data Check

In [2]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path("..") / "backend"))
from app.db.session import engine
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text('SELECT "Id", birthdate, zip FROM patients LIMIT 5'))
    for row in result:
        print(row)

('c44d667b-15d5-99d4-0f69-43ca66739022', datetime.date(1965, 8, 29), '01570')
('51c5e2a9-2833-5133-b85a-329b9cd53c41', datetime.date(1986, 1, 22), '00000')
('502cf42a-a540-ff39-0d59-c10d7cc1f4c7', datetime.date(2007, 4, 16), '02138')
('02459150-c160-03b6-f1dd-dae8fd4b3e84', datetime.date(1970, 4, 25), '00000')
('3237c17d-ea0b-90f4-0743-787ef29d2404', datetime.date(2025, 1, 11), '01247')

In [3]:
import os
os.getcwd()

'd:\\tss rao\\Portfolio Projects\\clinical-investigation-agent\\notebooks'

## Table Checks

In [5]:
from sqlalchemy import inspect

inspector = inspect(engine)
tables = inspector.get_table_names()
print(f"{len(tables)} tables:")
for t in sorted(tables):
    print(" -", t)

21 tables:
 - alembic_version
 - allergies
 - careplans
 - claims
 - claims_transactions
 - conditions
 - devices
 - encounters
 - imaging_studies
 - immunizations
 - loinc_codes
 - medications
 - observations
 - organizations
 - patients
 - payer_transitions
 - payers
 - procedures
 - providers
 - rxnorm_codes
 - supplies

## Phase 1 SQL Tool Check

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path("..") / "backend"))

from app.tools.sql_tool import (
    build_schema_context,
    execute_sql,
    format_report,
    is_select_only,
    load_join_safety_notes,
    run_sql_tool,
)

### 1. No-API-key checks: schema context, join notes, SQL safety guard, execution

In [2]:
# schema context is built from the live DB metadata, not hand-written - confirm it
# actually reflects the 20 real tables (21 minus alembic_version, which isn't a model)
schema_context = build_schema_context()
print(f"schema context: {len(schema_context)} chars, {len(schema_context.splitlines())} tables")
print(schema_context.splitlines()[:3])

join_notes = load_join_safety_notes()
print(f"\njoin_reference.md loaded: {len(join_notes)} chars")

schema context: 6908 chars, 20 tables
['allergies("id" BIGINT, "START" DATETIME, "STOP" DATETIME, "PATIENT" VARCHAR(36), "ENCOUNTER" VARCHAR(36), "CODE" VARCHAR(32), "SYSTEM" VARCHAR(128), "DESCRIPTION" VARCHAR(512), "TYPE" VARCHAR(16), "CATEGORY" VARCHAR(32), "REACTION1" VARCHAR(32), "DESCRIPTION1" VARCHAR(512), "SEVERITY1" VARCHAR(16), "REACTION2" VARCHAR(32), "DESCRIPTION2" VARCHAR(512), "SEVERITY2" VARCHAR(16))', 'careplans("Id" VARCHAR(36), "START" DATETIME, "STOP" DATETIME, "PATIENT" VARCHAR(36), "ENCOUNTER" VARCHAR(36), "CODE" VARCHAR(32), "DESCRIPTION" VARCHAR(512), "REASONCODE" VARCHAR(32), "REASONDESCRIPTION" VARCHAR(512))', 'claims("Id" VARCHAR(36), "PATIENTID" VARCHAR(36), "PROVIDERID" VARCHAR(36), "PRIMARYPATIENTINSURANCEID" VARCHAR(36), "SECONDARYPATIENTINSURANCEID" VARCHAR(36), "DEPARTMENTID" VARCHAR(32), "PATIENTDEPARTMENTID" VARCHAR(32), "DIAGNOSIS1" VARCHAR(32), "DIAGNOSIS2" VARCHAR(32), "DIAGNOSIS3" VARCHAR(32), "DIAGNOSIS4" VARCHAR(32), "DIAGNOSIS5" VARCHAR(32), "DIAGNOSIS6" VARCHAR(32), "DIAGNOSIS7" VARCHAR(32), "DIAGNOSIS8" VARCHAR(32), "REFERRINGPROVIDERID" VARCHAR(36), "APPOINTMENTID" VARCHAR(36), "CURRENTILLNESSDATE" DATETIME, "SERVICEDATE" DATETIME, "SUPERVISINGPROVIDERID" VARCHAR(36), "STATUS1" VARCHAR(16), "STATUS2" VARCHAR(16), "STATUSP" VARCHAR(16), "OUTSTANDING1" NUMERIC(12, 2), "OUTSTANDING2" NUMERIC(12, 2), "OUTSTANDINGP" NUMERIC(12, 2), "LASTBILLEDDATE1" DATETIME, "LASTBILLEDDATE2" DATETIME, "LASTBILLEDDATEP" DATETIME, "HEALTHCARECLAIMTYPEID1" VARCHAR(8), "HEALTHCARECLAIMTYPEID2" VARCHAR(8))']

join_reference.md loaded: 12988 chars

In [3]:
# SELECT-only safety guard - must reject anything destructive before it ever reaches execute_sql
print(is_select_only("SELECT * FROM patients"))                                # True
print(is_select_only("DELETE FROM patients"))                                   # False
print(is_select_only("SELECT * FROM patients; DROP TABLE patients;"))           # False

# execute_sql against the real DB - valid query
rows, error = execute_sql('SELECT count(*) AS n FROM patients')
print(rows, error)

# execute_sql against an invalid query - should return an error string, not raise
rows, error = execute_sql("SELECT * FROM not_a_real_table")
print(rows, error)

True
False
False
[{'n': 2338}] None
[] relation "not_a_real_table" does not exist
LINE 1: SELECT * FROM not_a_real_table
                      ^

### 2. Full NL->SQL pipeline (requires OPENAI_API_KEY set in .env)

In [4]:
from app.core.config import settings

if not settings.openai_api_key:
    print("OPENAI_API_KEY is not set in .env - skipping. Add a key to .env, then re-run this cell.")
else:
    questions = [
        "How many patients are there in total?",
        "How many distinct patients have at least one condition recorded?",
        "What are the 5 most common condition descriptions?",
    ]
    for q in questions:
        result = run_sql_tool(q)
        print(format_report(result))
        print("SQL:", result.sql)
        print("-" * 80)

'How many patients are there in total?' - 1 row(s):
  count=2338
SQL: SELECT COUNT(*) FROM patients;
--------------------------------------------------------------------------------
'How many distinct patients have at least one condition recorded?' - 1 row(s):
  count=2338
SQL: SELECT COUNT(DISTINCT "PATIENT") FROM conditions;
--------------------------------------------------------------------------------
'What are the 5 most common condition descriptions?' - 5 row(s):
  DESCRIPTION=Medication review due (situation), count=16831
  DESCRIPTION=Stress (finding), count=6571
  DESCRIPTION=Gingivitis (disorder), count=6384
  DESCRIPTION=Full-time employment (finding), count=6153
  DESCRIPTION=Part-time employment (finding), count=3739
SQL: SELECT "DESCRIPTION", COUNT(*) AS "count"
FROM conditions
GROUP BY "DESCRIPTION"
ORDER BY "count" DESC
LIMIT 5;
--------------------------------------------------------------------------------

In [5]:
# A destructive-intent question must never actually execute anything but SELECT,
# regardless of how the LLM responds to it.
if settings.openai_api_key:
    result = run_sql_tool("Delete all patients from the database")
    print(format_report(result))
    print("SQL:", result.sql)
    if result.success:
        assert is_select_only(result.sql), "destructive SQL slipped through!"
        print("OK: only a SELECT was executed")

'Delete all patients from the database' - 2338 row(s):
  Id=c44d667b-15d5-99d4-0f69-43ca66739022, birthdate=1965-08-29, deathdate=None, ssn=999-61-1158, drivers=S99942359, passport=X90357234X, prefix=Mrs., first=Azalee124, middle=None, last=Rippin620, suffix=None, maiden=Streich926, marital=D, race=white, ethnicity=nonhispanic, gender=F, birthplace=Hudson  Massachusetts  US, address=102 Conroy Camp, city=Webster, state=Massachusetts, county=Worcester County, fips=25027, zip=01570, lat=42.04627345067667, lon=-71.83245902860135, healthcare_expenses=481568.96, healthcare_coverage=242241.60, income=40621.00
  Id=51c5e2a9-2833-5133-b85a-329b9cd53c41, birthdate=1986-01-22, deathdate=None, ssn=999-92-7443, drivers=S99972916, passport=X87842688X, prefix=Mr., first=Merrill415, middle=Bernard308, last=Johnson679, suffix=JD, maiden=None, marital=D, race=white, ethnicity=nonhispanic, gender=M, birthplace=Saugus  Massachusetts  US, address=175 Walker Skyway Apt 94, city=Cochituate, state=Massachusetts, county=Middlesex County, fips=None, zip=00000, lat=42.28482107732429, lon=-71.35470077589272, healthcare_expenses=408183.15, healthcare_coverage=293397.78, income=53297.00
  Id=502cf42a-a540-ff39-0d59-c10d7cc1f4c7, birthdate=2007-04-16, deathdate=None, ssn=999-84-7678, drivers=S99975791, passport=None, prefix=Ms., first=Aletha771, middle=Isabell86, last=Ondricka197, suffix=None, maiden=None, marital=None, race=white, ethnicity=nonhispanic, gender=F, birthplace=Cohasset  Massachusetts  US, address=234 Powlowski Loaf Suite 94, city=Belmont, state=Massachusetts, county=Middlesex County, fips=25017, zip=02138, lat=42.3621271624251, lon=-71.19707066134303, healthcare_expenses=71276.61, healthcare_coverage=538108.50, income=526968.00
  Id=02459150-c160-03b6-f1dd-dae8fd4b3e84, birthdate=1970-04-25, deathdate=None, ssn=999-14-5874, drivers=S99948951, passport=X56279905X, prefix=Mrs., first=Cathy455, middle=None, last=Gleason633, suffix=None, maiden=Wintheiser220, marital=M, race=white, ethnicity=nonhispanic, gender=F, birthplace=Northampton  Massachusetts  US, address=833 Rippin Lock Unit 28, city=Douglas, state=Massachusetts, county=Worcester County, fips=None, zip=00000, lat=42.069462455916415, lon=-71.78433409121546, healthcare_expenses=296834.71, healthcare_coverage=1506701.17, income=168634.00
  Id=3237c17d-ea0b-90f4-0743-787ef29d2404, birthdate=2025-01-11, deathdate=None, ssn=999-94-6423, drivers=None, passport=None, prefix=None, first=Zada604, middle=Teisha100, last=Metz686, suffix=None, maiden=None, marital=None, race=white, ethnicity=nonhispanic, gender=F, birthplace=Swansea  Massachusetts  US, address=696 Becker Wynd, city=North Adams, state=Massachusetts, county=Berkshire County, fips=25003, zip=01247, lat=42.62760023278892, lon=-73.13198110816032, healthcare_expenses=500.00, healthcare_coverage=5931.33, income=23153.00
  Id=2cc66df7-5285-773c-7e50-639c378fb1e1, birthdate=1975-03-16, deathdate=None, ssn=999-51-6452, drivers=S99929728, passport=X11530575X, prefix=Mrs., first=Elnora999, middle=Sandy901, last=O'Conner199, suffix=None, maiden=Conroy74, marital=M, race=white, ethnicity=nonhispanic, gender=F, birthplace=The Pinehills  Massachusetts  US, address=886 Nader Bay Apt 54, city=Holyoke, state=Massachusetts, county=Hampden County, fips=25013, zip=01040, lat=42.19828849870062, lon=-72.63212270429031, healthcare_expenses=807235.86, healthcare_coverage=151881.97, income=62065.00
  Id=558cb393-3418-a056-95cc-3dc73759409c, birthdate=1997-03-09, deathdate=None, ssn=999-18-6004, drivers=S99940041, passport=X74054966X, prefix=Mrs., first=Arlene209, middle=Dorathy429, last=Nader710, suffix=None, maiden=West559, marital=M, race=white, ethnicity=nonhispanic, gender=F, birthplace=Bourne  Massachusetts  US, address=784 Mayer Ramp, city=Springfield, state=Massachusetts, county=Hampden County, fips=25013, zip=01105, lat=42.06879671032237, lon=-72.49111809160144, healthcare_expenses=48264.41, healthcare_coverage=1566239.66, income=23809.00
  Id=cae5cd45-be24-6020-45c8-d1bdd1ef363b, birthdate=1957-06-05, deathdate=None, ssn=999-41-3685, drivers=S99948643, passport=X81311628X, prefix=Mr., first=Merlin721, middle=Dillon740, last=Bradtke547, suffix=None, maiden=None, marital=S, race=black, ethnicity=hispanic, gender=M, birthplace=Halifax  Massachusetts  US, address=894 Simonis Branch Apt 23, city=Boston, state=Massachusetts, county=Suffolk County, fips=25025, zip=02120, lat=42.38492055326165, lon=-71.04134013623914, healthcare_expenses=214017.18, healthcare_coverage=139724.29, income=111802.00
  Id=13c4624a-99af-ed39-763b-09586c37814c, birthdate=2021-04-26, deathdate=None, ssn=999-69-4042, drivers=None, passport=None, prefix=None, first=Chery887, middle=None, last=Thompson596, suffix=None, maiden=None, marital=None, race=white, ethnicity=nonhispanic, gender=F, birthplace=Lowell  Massachusetts  US, address=1023 Dicki Glen, city=Hanson, state=Massachusetts, county=Plymouth County, fips=25023, zip=02341, lat=42.091881969983206, lon=-70.86548794668187, healthcare_expenses=15868.31, healthcare_coverage=64.40, income=150885.00
  Id=1f130f26-588f-6a23-7add-6c93e1cce600, birthdate=1981-11-19, deathdate=2023-10-10, ssn=999-36-6243, drivers=S99933111, passport=X06930749X, prefix=Mr., first=Jason347, middle=None, last=Nader710, suffix=None, maiden=None, marital=M, race=white, ethnicity=nonhispanic, gender=M, birthplace=Quincy  Massachusetts  US, address=929 Gusikowski View Suite 45, city=Gardner, state=Massachusetts, county=Worcester County, fips=25027, zip=01440, lat=42.61962454464914, lon=-72.0177309589684, healthcare_expenses=9666.48, healthcare_coverage=677314.11, income=8681.00
  Id=ab7ffb81-5b2c-e177-4baa-13e1c7406719, birthdate=2016-08-14, deathdate=None, ssn=999-89-4810, drivers=None, passport=None, prefix=None, first=Cruz300, middle=None, last=Cassin499, suffix=None, maiden=None, marital=None, race=white, ethnicity=nonhispanic, gender=M, birthplace=Woburn  Massachusetts  US, address=443 Veum Annex Apt 25, city=Monson, state=Massachusetts, county=Hampden County, fips=None, zip=00000, lat=42.11591786804244, lon=-72.27253868994922, healthcare_expenses=12916.55, healthcare_coverage=8745.20, income=603276.00
  Id=6097e81b-28de-31e8-7a14-911bb71635d2, birthdate=1995-11-29, deathdate=None, ssn=999-30-5635, drivers=S99949516, passport=X04773923X, prefix=Mr., first=Gregory545, middle=Gene733, last=Quigley282, suffix=None, maiden=None, marital=M, race=white, ethnicity=nonhispanic, gender=M, birthplace=Attleboro  Massachusetts  US, address=540 Kuhn Byway, city=Boston, state=Massachusetts, county=Suffolk County, fips=25025, zip=02136, lat=42.274066805310056, lon=-71.11247194442963, healthcare_expenses=102505.44, healthcare_coverage=15458.14, income=45531.00
  Id=e3d28426-1f6f-929b-1eea-8cdd8f21c8e4, birthdate=2005-11-14, deathdate=None, ssn=999-42-4866, drivers=S99920864, passport=X18757882X, prefix=Ms., first=Stella203, middle=Wonda35, last=Towne435, suffix=None, maiden=None, marital=None, race=white, ethnicity=nonhispanic, gender=F, birthplace=Billerica  Massachusetts  US, address=255 Langworth Course Suite 49, city=South Amherst, state=Massachusetts, county=Hampshire County, fips=None, zip=00000, lat=42.332592523395874, lon=-72.55962059997421, healthcare_expenses=68469.65, healthcare_coverage=12551.85, income=39371.00
  Id=f7aae009-49cd-ad5f-7643-ad17fe36e74a, birthdate=1981-11-19, deathdate=None, ssn=999-76-6690, drivers=S99961979, passport=X35154880X, prefix=Mr., first=Irvin970, middle=Howard613, last=Medhurst46, suffix=None, maiden=None, marital=M, race=white, ethnicity=nonhispanic, gender=M, birthplace=Carver  Massachusetts  US, address=757 Dare Wynd, city=Gardner, state=Massachusetts, county=Worcester County, fips=25027, zip=01440, lat=42.60690090634195, lon=-71.98990082499168, healthcare_expenses=11113.54, healthcare_coverage=250637.35, income=8681.00
  Id=01674483-f178-6116-5d61-9f74713bde4c, birthdate=1980-01-06, deathdate=None, ssn=999-15-5811, drivers=S99945410, passport=X45276270X, prefix=Mr., first=Luther918, middle=Rolland302, last=Hartmann983, suffix=None, maiden=None, marital=M, race=white, ethnicity=nonhispanic, gender=M, birthplace=Williamstown  Massachusetts  US, address=246 Christiansen Frontage road, city=West Newbury, state=Massachusetts, county=Essex County, fips=None, zip=00000, lat=42.84711146279092, lon=-70.9862353171455, healthcare_expenses=97462.54, healthcare_coverage=643658.09, income=199757.00
  Id=d512b902-a07c-392e-d6dc-94e24e6ff7ab, birthdate=1984-01-30, deathdate=None, ssn=999-62-6540, drivers=S99974712, passport=X36816577X, prefix=Mr., first=Gregory545, middle=None, last=Moore224, suffix=None, maiden=None, marital=M, race=white, ethnicity=nonhispanic, gender=M, birthplace=Boston  Massachusetts  US, address=400 Osinski Junction Apt 67, city=Kingston, state=Massachusetts, county=Plymouth County, fips=25023, zip=02364, lat=42.03353233231295, lon=-70.78888990517879, healthcare_expenses=118820.66, healthcare_coverage=13934.06, income=163487.00
  Id=b15aeab3-19eb-b423-ec20-de182ca4a638, birthdate=1970-01-07, deathdate=None, ssn=999-60-6827, drivers=S99927282, passport=X33218474X, prefix=Mr., first=Emerson869, middle=Sean831, last=Schaefer657, suffix=None, maiden=None, marital=M, race=white, ethnicity=nonhispanic, gender=M, birthplace=Boston  Massachusetts  US, address=231 Powlowski Rapid, city=Pittsfield, state=Massachusetts, county=Berkshire County, fips=25003, zip=01201, lat=42.44427695231909, lon=-73.30468566224513, healthcare_expenses=179257.45, healthcare_coverage=131883.88, income=58597.00
  Id=e1b14cdb-c074-01c7-c2e4-e913ede77e91, birthdate=1977-04-11, deathdate=None, ssn=999-71-2283, drivers=S99977906, passport=X26091485X, prefix=Mrs., first=Adelina682, middle=Ozella681, last=Gleichner915, suffix=None, maiden=Schoen8, marital=M, race=white, ethnicity=nonhispanic, gender=F, birthplace=Boston  Massachusetts  US, address=1054 Davis Terrace, city=Methuen, state=Massachusetts, county=Essex County, fips=25009, zip=01841, lat=42.68187416656385, lon=-71.20908963216486, healthcare_expenses=272583.69, healthcare_coverage=360275.03, income=69794.00
  Id=df3d1431-6180-3c44-0d77-214a2ff54ff1, birthdate=2001-06-21, deathdate=None, ssn=999-32-3382, drivers=S99947339, passport=X98671598X, prefix=Ms., first=Chantay958, middle=Malka46, last=Conroy74, suffix=None, maiden=None, marital=None, race=white, ethnicity=nonhispanic, gender=F, birthplace=North Andover  Massachusetts  US, address=400 Harvey Flat, city=Plainville, state=Massachusetts, county=Norfolk County, fips=None, zip=00000, lat=41.98463407725638, lon=-71.35632045895794, healthcare_expenses=158243.84, healthcare_coverage=739072.96, income=110869.00
  Id=13bd553e-8de6-7e08-52eb-04ec8ed678d4, birthdate=2008-03-30, deathdate=None, ssn=999-98-2558, drivers=S99981574, passport=None, prefix=Ms., first=Shirl54, middle=Jeanett771, last=Schaden604, suffix=None, maiden=None, marital=None, race=white, ethnicity=nonhispanic, gender=F, birthplace=Marion  Massachusetts  US, address=948 Dicki Glen Apt 10, city=Bourne, state=Massachusetts, county=Barnstable County, fips=25001, zip=02532, lat=41.687553109310194, lon=-70.63606206388677, healthcare_expenses=43790.66, healthcare_coverage=0.00, income=79444.00
  ... and 2318 more
SQL: SELECT * FROM patients;
OK: only a SELECT was executed